name: vrunoa.me

on:
  pull_request:
    branches:
      - main
#  push:
#    tags:
#      - v*

env:
  GH_TOKEN: ${{secrets.GH_TOKEN}}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node version
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run clear && npm run build

      - name: Create tarball
        run: |
          push build
          tar -cvf build.tar.gz ./*
          popd
          npm run clear

      - name: Update gh-pages
        run: |
          git checkout gh-pages
          tar xvfz build.tar.gz -C ./
          git status
